### ISSUE TITLE
`CrosshairInternal` on nested properties

### ISSUE THREAD

**Issue by tybug** [pschanely/hypothesis-crosshair#11]
```python
from hypothesis import given, settings
from hypothesis import strategies as st

settings.register_profile("crosshair", backend="crosshair", deadline=None)
settings.load_profile("crosshair")

@given(st.integers())
def outer(n1):
    @given(st.integers(min_value=n1, max_value=n1))
    def inner(n2):
        assert n1 == n2
    inner()
outer()
```

stacktrace:
```python
  ... (truncated)

  File "/Users/tybug/Desktop/Liam/coding/sandbox/hypothesis_/sandbox4.py", line 36, in outer
    def outer(n1):
                   
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 830, in test
    return self.test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tybug/Desktop/Liam/coding/sandbox/hypothesis_/sandbox4.py", line 37, in outer
    @given(st.integers(min_value=n1, max_value=n1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/strategies/_internal/numbers.py", line 112, in integers
    @defines_strategy(force_reusable_values=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/strategies/_internal/utils.py", line 79, in cached_strategy
    if cache_key in cache:
       ^^^^^^^^^^^^^^^^^^
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/cache.py", line 97, in __contains__
    return key in self.keys_to_indices
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/crosshair/libimpl/builtinslib.py", line 908, in __eq__
    return numeric_binop(ops.eq, self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/crosshair/libimpl/builtinslib.py", line 462, in numeric_binop
    raise CrosshairInternal("Numeric operation on symbolic while not tracing")
crosshair.util.CrosshairInternal: Numeric operation on symbolic while not tracing
```

I think we're using the kwargs to `st.integers` as a cache key to reuse strategies, which includes `n1`, and somehow `n1` is realized outside of a crosshair scope (or maybe just outside of its own `outer` crosshair scope since we may have jumped to a new one with `inner`?).

Idle musing: something we should consider more broadly is nested backend scopes. A user may request backend A on `outer` and a different backend B on `inner`. Ideally this would just work™️, but of course it may not be that simple to support.

Counterexample extracted from https://github.com/HypothesisWorks/hypothesis/blob/d8c17832141f587fec9ef89895ed01a4e9c1650d/hypothesis-python/tests/cover/test_datetimes.py#L52-L54.

**Comment by tybug** [comment]
hmm, I was ready to declare this a hypothesis-side issue which needs `realize` calls added in more places, but even if I realize `n1` with `print(n1)` before `@given(...)inner` I get the same error. So I'm no longer sure as to the cause here.

**Comment by pschanely** [comment]
> hmm, I was ready to declare this a hypothesis-side issue which needs `realize` calls added in more places, but even if I realize `n1` with `print(n1)` before `@given(...)inner` I get the same error. So I'm no longer sure as to the cause here.

Although `print(n1)` will "realize" the value, the `n1` variable remains symbolic - it is just a symbolic that is constrained in the solver to only take on a single value. Unfortunately, the only way to get a native Python value is via the return value from `realize` or `deep_realize`.

But backing up ... oh wow. I had not anticipated this kind of nesting as a hypothesis use case. (IIUC, at the default 100 iterations, this runs `inner()` 10k times?!) First, I'm not at all confident that my plugin (or more fundamentally, CrossHair) can be re-entrant in this manner. It **might** work; I'm just not sure. Even if it worked, this means that MUCH more of the hypothesis internal code will be run under CrossHair, and CrossHair is so sensitive about nondeterminism that I'm not sure it could work in practice (internal caches, the persistent database file, etc).

**Comment by tybug** [comment]
> Unfortunately, the only way to get a native Python value is via the return value from realize or deep_realize

my mistake, thanks for the correction.

> 10k

The linked hypothesis example is a bit more reasonable as `assert_simple_property` limits to 15 examples, so 1500 total. But yeah I'd expect nested properties to be a relatively rare use case due to the quadratic runtime.

I think "don't nest properties" is a valid limitation for the time being (and maybe indefinitely), and we could document this hypothesis-crosshair-side and skip affected tests hypothesis-side for `backend="crosshair"`. I'll cc @Zac-HD in here as well.

**Comment by Zac-HD** [comment]
Ouch, yeah, trying to support nesting seems pretty tough.  I definitely support documenting this as a limitation and moving on (with a nice error message if possible).

**Comment by tybug** [comment]
Here's a more clear stacktrace with the latest release:

```python
@given(st.integers())
def outer(n1):
    @given(st.integers())
    def inner(n2):
        pass
    inner()
outer()
```

```python
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/hypothesis_crosshair_provider/crosshair_provider.py", line 90, in per_test_case_context_manager
    with (
  File "/opt/homebrew/lib/python3.12/site-packages/crosshair/statespace.py", line 228, in __enter__
    assert prev is None, "Already in a state space context"
           ^^^^^^^^^^^^
AssertionError: Already in a state space context
```

**Comment by tybug** [comment]
A hypothesis-side update: we had previously discussed the possibility of making nested `@given` an error, but have instead made it into a health check failure that can be suppressed. This means that crosshair will have to continue checking for `@given` nesting and raising an exception if so - which it already does, so no change necessary! I think this issue is now safe to close.

See https://github.com/HypothesisWorks/hypothesis/issues/4167.
