### ISSUE TITLE
Infinite recursion with nested properties

### ISSUE THREAD

**Issue by tybug** [pschanely/hypothesis-crosshair#12]
It's possible this is a symptom of a separate issue. I haven't looked into it and am just logging it to ensure we don't forget.

This seems superficially similar to #11, but I don't know if it's related. I don't know if using `timedelta` is critical to reproducing or not (when I tried to manually shrink via `st.timedeltas` -> `st.integers`, I got #11).

```python
@given(st.timedeltas())
def outer(val):
    @given(st.timedeltas(min_value=val, max_value=val))
    def inner(v):
        assert v == val
    inner()
outer()
```

```python
Traceback (most recent call last):
  File "/Users/tybug/Desktop/Liam/coding/sandbox/hypothesis_/sandbox4.py", line 31, in <module>
    outer()
  File "/Users/tybug/Desktop/Liam/coding/sandbox/hypothesis_/sandbox4.py", line 26, in outer
    def outer(val):
                   ^
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1657, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1624, in wrapped_test
    state.run_engine()
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/core.py", line 1152, in run_engine
    runner.run()
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 757, in run
    self._run()
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 1219, in _run
    self.generate_new_examples()
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 975, in generate_new_examples
    self.test_function(data)
  File "/Users/tybug/Desktop/Liam/coding/hypothesis/hypothesis-python/src/hypothesis/internal/conjecture/engine.py", line 531, in test_function
    raise Flaky(
hypothesis.errors.Flaky: Inconsistent results from replaying a failing test case!
  last: INTERESTING from RecursionError at /opt/homebrew/lib/python3.12/site-packages/crosshair/tracers.py:163
  this: OVERRUN
```

**Comment by tybug** [comment]
I think the flaky here was an interplay between #13 and #11. Now that the former is fixed, I'm fairly certain this is a duplicate of the latter.
